### ISSUE TITLE
Issue with Append

### ISSUE THREAD

**Issue by iuchavez** [tanmark927/327-DFS#20]
I opened up three clients / nodes on our DFS. Then joined them together and created a file called "filename"

then on another node I typed in the append command and input the following:
'Type in an option number: 8
Enter File to append to: filename
Enter filepath for appending data (default: 327FS.json): cat.txt'

Here was the result in the 327FS.json

<img width="306" alt="screen shot 2018-04-14 at 3 16 21 pm" src="https://user-images.githubusercontent.com/18611839/38772927-cf7bcbe6-3ff6-11e8-84b9-4d25a30be4b0.png">

**Comment by iuchavez** [comment]
The file called "filenamepage0" was created even though all I did was an append operation.

**Comment by tanmark927** [comment]
that is supposed to happen. if you look at the instructions, it says that each page is supposed to be a file in the metadata.

**Comment by iuchavez** [comment]
After chatting about this we came to an agreement to have a page exist under a file only.
